#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : libsrtp
Version  : 2.5
Release  : 7
URL      : https://github.com/cisco/libsrtp/archive/v2.5/libsrtp-2.5.tar.gz
Source0  : https://github.com/cisco/libsrtp/archive/v2.5/libsrtp-2.5.tar.gz
Summary  : Library for SRTP (Secure Realtime Transport Protocol)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libsrtp-lib = %{version}-%{release}
Requires: libsrtp-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : libpcap-dev
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(nss)
BuildRequires : sed
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Set-libsrtp.pc-to-require-libpcap.pc.patch

%description
[![CMake Build](https://github.com/cisco/libsrtp/actions/workflows/cmake.yml/badge.svg)](https://github.com/cisco/libsrtp/actions/workflows/cmake.yml)
[![Autotools Build](https://github.com/cisco/libsrtp/actions/workflows/autotools.yml/badge.svg)](https://github.com/cisco/libsrtp/actions/workflows/autotools.yml)
[![Build Status](https://travis-ci.org/cisco/libsrtp.svg?branch=master)](https://travis-ci.org/cisco/libsrtp)
[![Coverity Scan Build Status](https://scan.coverity.com/projects/14274/badge.svg)](https://scan.coverity.com/projects/cisco-libsrtp)
[![OSS-Fuzz Status](https://oss-fuzz-build-logs.storage.googleapis.com/badges/systemd.svg)](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libsrtp)

%package dev
Summary: dev components for the libsrtp package.
Group: Development
Requires: libsrtp-lib = %{version}-%{release}
Provides: libsrtp-devel = %{version}-%{release}
Requires: libsrtp = %{version}-%{release}

%description dev
dev components for the libsrtp package.


%package lib
Summary: lib components for the libsrtp package.
Group: Libraries
Requires: libsrtp-license = %{version}-%{release}

%description lib
lib components for the libsrtp package.


%package license
Summary: license components for the libsrtp package.
Group: Default

%description license
license components for the libsrtp package.


%prep
%setup -q -n libsrtp-2.5
cd %{_builddir}/libsrtp-2.5
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689619601
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}  shared_library

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
export SOURCE_DATE_EPOCH=1689619601
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libsrtp
cp %{_builddir}/libsrtp-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libsrtp/e8a22b77b707f4d8fc8cb2f86c117fd8f7251635 || :
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/srtp2/auth.h
/usr/include/srtp2/cipher.h
/usr/include/srtp2/crypto_types.h
/usr/include/srtp2/srtp.h
/usr/lib64/libsrtp2.so
/usr/lib64/pkgconfig/libsrtp2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsrtp2.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libsrtp/e8a22b77b707f4d8fc8cb2f86c117fd8f7251635
