#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libsrtp
Version  : 1.6.0
Release  : 3
URL      : https://github.com/cisco/libsrtp/archive/v1.6.0.tar.gz
Source0  : https://github.com/cisco/libsrtp/archive/v1.6.0.tar.gz
Summary  : Library for SRTP (Secure Realtime Transport Protocol)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libsrtp-lib

%description
Secure RTP (SRTP) Reference Implementation
David A. McGrew
Cisco Systems, Inc.
mcgrew@cisco.com

%package dev
Summary: dev components for the libsrtp package.
Group: Development
Requires: libsrtp-lib
Provides: libsrtp-devel

%description dev
dev components for the libsrtp package.


%package lib
Summary: lib components for the libsrtp package.
Group: Libraries

%description lib
lib components for the libsrtp package.


%prep
%setup -q -n libsrtp-1.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1521242509
%configure --disable-static
make  %{?_smp_mflags} shared_library

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
export SOURCE_DATE_EPOCH=1521242509
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/srtp/aes.h
/usr/include/srtp/aes_cbc.h
/usr/include/srtp/aes_gcm_ossl.h
/usr/include/srtp/aes_icm.h
/usr/include/srtp/aes_icm_ossl.h
/usr/include/srtp/alloc.h
/usr/include/srtp/auth.h
/usr/include/srtp/cipher.h
/usr/include/srtp/config.h
/usr/include/srtp/crypto.h
/usr/include/srtp/crypto_kernel.h
/usr/include/srtp/crypto_math.h
/usr/include/srtp/crypto_types.h
/usr/include/srtp/cryptoalg.h
/usr/include/srtp/datatypes.h
/usr/include/srtp/ekt.h
/usr/include/srtp/err.h
/usr/include/srtp/getopt_s.h
/usr/include/srtp/gf2_8.h
/usr/include/srtp/hmac.h
/usr/include/srtp/integers.h
/usr/include/srtp/kernel_compat.h
/usr/include/srtp/key.h
/usr/include/srtp/null_auth.h
/usr/include/srtp/null_cipher.h
/usr/include/srtp/prng.h
/usr/include/srtp/rand_source.h
/usr/include/srtp/rdb.h
/usr/include/srtp/rdbx.h
/usr/include/srtp/rtp.h
/usr/include/srtp/rtp_priv.h
/usr/include/srtp/sha1.h
/usr/include/srtp/srtp.h
/usr/include/srtp/srtp_priv.h
/usr/include/srtp/stat.h
/usr/include/srtp/ut_sim.h
/usr/include/srtp/xfm.h
/usr/lib64/libsrtp.so
/usr/lib64/pkgconfig/libsrtp.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsrtp.so.1
